name: Deploy getrefactor.com

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: python -m pip install panel==0.14.0 refactor==0.6.2

    - name: Build the page
      shell: python
      run: |
        import subprocess
        import shutil
        from pathlib import Path

        BASE_DIR = Path()
        INPUT_FILE = BASE_DIR / "index.py"
        OUTPUT_DIR = BASE_DIR / "_site"
        CNAME_FILE = BASE_DIR / "CNAME"
        CONVERSION_TYPE = "pyodide-worker"
        DEPENDENCIES = "refactor==0.6.2"

        subprocess.check_output(
            [
                "panel",
                "convert",
                INPUT_FILE,
                "--to",
                CONVERSION_TYPE,
                "--out",
                OUTPUT_DIR,
                "--requirements",
                *DEPENDENCIES.split(" "),
            ]
        )

        if CNAME_FILE:
            shutil.copy(CNAME_FILE, OUTPUT_DIR)

        if CONVERSION_TYPE == "pyodide-worker":
            # Fixup the wrong JSON serialization when using
            # panel convert with pyodide-worker.

            output_file = OUTPUT_DIR / INPUT_FILE.with_suffix(".js")
            source_code = output_file.read_text()
            source_code = source_code.replace(
                "json.loads('${msg.patch}')",
                "json.loads(${JSON.stringify(msg.patch)})",
            )
            output_file.write_text(source_code)

    - name: Upload a Build Artifact
      uses: actions/upload-pages-artifact@v1.0.4

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
